name: NN
on:
  - pull_request
  - push
jobs:
  run:
    runs-on: self-hosted
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: "run builds (with neural network)"
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .[nn]
