name: Linux
on:
  - pull_request
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: "run builds (without neural network)"
        run: |
          git describe --tags
          pip install -e .[normal]
