name: build-nn
on:
  - pull_request
jobs:
  run:
    runs-on: self-hosted
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: "run tests (with neural network)"
        run: |
          pip install pytest
          pip install -e .[nn]
          pytest tests/
