name: build
on:
  - pull_request
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: "run tests (without neural network)"
        run: |
          pip install -r requirements.txt
          python main.py --data_folder example/example_data --train_data heart --response HeartDisease --max_evals 32
          python main.py --data_folder example/example_data --train_data insurance --response expenses --max_evals 32
