name: build
on: pull_request
jobs:
  run:
    runs-on: self-hosted
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: "generate report"
        run: |
          pip install coverage pytest
          pip install -r requirements.txt
          python main.py --data_folder example/example_data --train_data heart --response HeartDisease
          python main.py --data_folder example/example_data --train_data insurance --response expenses
