name: Linux
on:
  - pull_request
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: "run builds (without neural network)"
        run: |
          pip install pytest
          pip install -e .[normal]
