name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: "generate report"
        run: |
          conda activate pytorch
          coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
