name: CodeCov
on:
  - pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      	with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: "generate report"
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest
          pip install -e .[extended]
          coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: uitests
          fail_ci_if_error: false
          verbose: true
