# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload PyPI Release

on:
  release:
    types:
      - published
  # pull_request:
  # push:

jobs:
  build_wheel_on_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine cython auditwheel patchelf>=0.14
          # sudo apt-get install patchelf
      - name: Build # and publish
        # env:
        #   TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        #   TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel

          # build manylinux wheel
          auditwheel repair dist/*-linux_x86_64.whl -w dist/ --plat manylinux_2_24_x86_64
          # auditwheel repair dist/*.whl
          # remove original whl files
          rm -r -f dist/*-linux_x86_64.whl

          # # twine upload [[lib]]-manylinux_2_24_x86_64.whl
          # twine upload dist/*
      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  build_wheel_on_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine cython auditwheel patchelf>=0.14
          # sudo apt-get install patchelf
      - name: Build # and publish
        # env:
        #   TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        #   TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel

          # remove source files
          del dist\*.tar.gz

      - name: Upload to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels, build_sdist]

    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
# name: Upload PyPI Releaseld

# on:
#   release:
#     types:
#       - published
#   pull_request:
#   # push:

# jobs:
#   # build_sdist :
#   #   name : Build distribution on Linux
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@master
#   #     - name: Set up Python
#   #       uses: actions/setup-python@master
#   #       with:
#   #         python-version: 3.9
#   #     - name: Install dependencies
#   #       run: |
#   #         python -m pip install --upgrade pip
#   #         pip install setuptools wheel twine cython auditwheel patchelf>=0.14
#   #         # sudo apt-get install patchelf
#   #     - name: Build and publish
#   #       env:
#   #         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#   #         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#   #       run: |
#   #         python setup.py sdist bdist_wheel

# build_wheels:
#   name: Build wheels on ${{ matrix.os }}
#   runs-on: ${{ matrix.os }}
#   strategy:
#     matrix:
#       os: [ubuntu-latest, windows-latest]
#       python_version:
#         - 3.8
#         - 3.9

#   steps:
#     - uses: actions/checkout@master
#     # - name: Set up Python
#     #   uses: actions/setup-python@master
#     #   with:
#     #     python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install setuptools wheel twine cython cibuildwheel
#         # pip install auditwheel patchelf>=0.14
#         # sudo apt-get install patchelf

#     - name: Build wheels
#       run: python -m cibuildwheel --output-dir dist
#       # to supply options, put them in 'env', like:
#       # env:
#       #   CIBW_SOME_OPTION: value
#     - uses: actions/upload-artifact@v3
#       with:
#         path: ./dist/*

#     # - name: Publish to PyPI
#     #   env:
#     #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#     #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     #   run: |
#     #     twine upload dist/*

# publish:
#   name: Publish to PyPI
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/upload-artifact@v3
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install setuptools wheel twine cython cibuildwheel
#     - name: publish
#       env:
#         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#       run: |
#         twine upload dist/*
